name = "vr-www-signatures-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-08"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "personal-site"
database_id = "e903d5ec-aa82-4080-af4c-ba8c11e01875"
