# fly.toml app configuration file generated for vrogg-site on 2023-09-25T09:13:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vrogg-site"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
