# deploy.toml app configuration file generated for vrogg-site on 2023-09-25T14:49:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vrogg-site"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
