name: Fly Staging Deploy

on:
  push:
    branches: [dev]

jobs:

  deploy-app:
    name: Deploy staging app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy \
          --config fly.staging.toml \
          --build-secret PUBLIC_CF_IMAGES_ENDPOINT=${{ secrets.PUBLIC_CF_IMAGES_ENDPOINT }} \
          --build-secret PUBLIC_STORYBLOK_TOKEN=${{ secrets.PUBLIC_STORYBLOK_TOKEN }} \
          --build-secret PUBLIC_POSTHOG_TOKEN=${{ secrets.PUBLIC_POSTHOG_TOKEN }} \
          --build-secret PUBLIC_VERSION_DATE=${{ github.event.head_commit.timestamp }} \
          --build-secret PUBLIC_SIGNATURES_WORKER=${{ secrets.PUBLIC_SIGNATURES_WORKER }} \
          --build-secret ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
          --build-secret WORKER_PSK=${{ secrets.WORKER_PSK }} \
          --build-secret RESEND_TOKEN=${{ secrets.RESEND_TOKEN }} \
          --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-workers:
    name: Deploy workers
    uses: ./.github/workflows/workers.yml
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}