name: CF Workers Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/ps-signatures"